from __future__ import annotations

import json
from dataclasses import asdict
from typing import Any

import requests

from ..config import settings
from .bankroll_manager import recommended_stake
from .data_sources import TeamContext


JSON_SCHEMA_HINT = {
    "prediction": "P1|X|P2|TБ2.5|BTTS|Other",
    "reasoning": "short explanation",
    "confidence": 1,
    "recommended_stake": 0.0,
}


def _team_context_to_text(match: TeamContext) -> str:
    return (
        f"League: {match.league}\n"
        f"Match: {match.home_team} vs {match.away_team}\n"
        f"Odds: {match.odds}\n"
        f"Home xG: {match.home_xg}\n"
        f"Away xG: {match.away_xg}\n"
        f"Home xGA: {match.home_xga}\n"
        f"Away xGA: {match.away_xga}\n"
        f"Home form: {match.home_form}\n"
        f"Away form: {match.away_form}\n"
        f"Injuries: {match.injuries}\n"
        f"Source notes: {match.source_notes}"
    )


def build_prediction_prompt(match: TeamContext, bankroll: float, confidence: float = 0.6) -> str:
    stake = recommended_stake(bankroll, confidence, strategy="flat")
    return (
        "You are a football betting analyst. Return ONLY valid JSON, no markdown. "
        f"Use this schema hint: {json.dumps(JSON_SCHEMA_HINT, ensure_ascii=False)}.\n"
        f"{_team_context_to_text(match)}\n"
        f"Metadata: {json.dumps(match.metadata, ensure_ascii=False)}\n"
        f"Current bankroll: {bankroll}\n"
        f"Suggested stake: {stake}\n"
        "Prefer safe, conservative recommendations and explicitly mention uncertainty."
    )


def _extract_json_payload(text: str) -> dict[str, Any]:
    text = text.strip()
    if text.startswith("```"):
        text = text.strip("`")
    start = text.find("{")
    end = text.rfind("}")
    if start == -1 or end == -1 or end <= start:
        raise ValueError("No JSON object found")
    return json.loads(text[start : end + 1])


def _normalize_prediction_payload(payload: dict[str, Any], bankroll: float) -> dict[str, Any]:
    prediction = str(payload.get("prediction") or payload.get("pick") or "BTTS")
    reasoning = str(payload.get("reasoning") or payload.get("analysis") or "")
    confidence = int(payload.get("confidence") or 3)
    recommended_stake_value = payload.get("recommended_stake")
    if recommended_stake_value is None:
        recommended_stake_value = recommended_stake(bankroll, confidence / 5.0, strategy="flat")
    return {
        "prediction": prediction,
        "reasoning": reasoning,
        "confidence": max(1, min(confidence, 5)),
        "recommended_stake": float(recommended_stake_value),
        "raw": payload,
    }


def mock_predict(match: TeamContext, bankroll: float) -> dict[str, object]:
    prompt = build_prediction_prompt(match, bankroll)
    return {
        "prediction": "BTTS",
        "reasoning": "Mock response generated by the local scaffold. Replace with a real LLM or inference endpoint.",
        "confidence": 3,
        "recommended_stake": recommended_stake(bankroll, 0.6, strategy="flat"),
        "prompt": prompt,
        "match": asdict(match),
    }


def _call_openai(prompt: str) -> dict[str, Any]:
    if not settings.openai_api_key:
        raise RuntimeError("OPENAI_API_KEY is not configured")

    response = requests.post(
        "https://api.openai.com/v1/chat/completions",
        headers={
            "Authorization": f"Bearer {settings.openai_api_key}",
            "Content-Type": "application/json",
        },
        json={
            "model": settings.openai_model,
            "messages": [
                {"role": "system", "content": "You are a concise football betting analyst."},
                {"role": "user", "content": prompt},
            ],
            "temperature": 0.2,
        },
        timeout=45,
    )
    response.raise_for_status()
    content = response.json()["choices"][0]["message"]["content"]
    return _extract_json_payload(content)


def _call_huggingface(prompt: str) -> dict[str, Any]:
    if not settings.hf_api_token:
        raise RuntimeError("HF_API_TOKEN is not configured")

    response = requests.post(
        f"{settings.hf_inference_url}/{settings.hf_model}",
        headers={
            "Authorization": f"Bearer {settings.hf_api_token}",
            "Content-Type": "application/json",
        },
        json={
            "inputs": prompt,
            "parameters": {
                "max_new_tokens": 512,
                "temperature": 0.2,
                "return_full_text": False,
            },
        },
        timeout=60,
    )
    response.raise_for_status()
    data = response.json()
    if isinstance(data, list) and data:
        generated = data[0].get("generated_text", "")
    elif isinstance(data, dict):
        generated = data.get("generated_text", "") or data.get("text", "")
    else:
        generated = ""
    return _extract_json_payload(str(generated))


def generate_prediction(match: TeamContext, bankroll: float) -> dict[str, object]:
    prompt = build_prediction_prompt(match, bankroll)
    try:
        if settings.ai_provider == "openai":
            payload = _call_openai(prompt)
            normalized = _normalize_prediction_payload(payload, bankroll)
            normalized["prompt"] = prompt
            normalized["match"] = asdict(match)
            return normalized
        if settings.ai_provider in {"hf", "huggingface"}:
            payload = _call_huggingface(prompt)
            normalized = _normalize_prediction_payload(payload, bankroll)
            normalized["prompt"] = prompt
            normalized["match"] = asdict(match)
            return normalized
    except Exception as exc:
        return {
            "prediction": "BTTS",
            "reasoning": f"Provider error, fallback used: {exc}",
            "confidence": 2,
            "recommended_stake": recommended_stake(bankroll, 0.4, strategy="flat"),
            "prompt": prompt,
            "match": asdict(match),
        }

    return mock_predict(match, bankroll)


def build_retro_report(predictions: list[dict[str, object]]) -> str:
    payload = {
        "total_predictions": len(predictions),
        "predictions": predictions,
        "summary": "Mock retrospective report. Replace with LLM analysis for real audits.",
    }
    return json.dumps(payload, ensure_ascii=False, indent=2)
